return {
  autostart = true,
  root_dir = require("lspconfig.util").root_pattern "*.ahk",
  cmd = {
    "node",
    "C:/APP_File/File_Data/Language Server Protocol/Autohotkey/server/dist/server.js",
    "--stdio",
  },
  filetypes = { "autohotkey", "ahk" },
  init_options = {
    locale = "zh-cn",
    AutoLibInclude = "Disabled",
    CommentTags = "^;;\\s*(?<tag>.+)",
    CompleteFunctionParens = false,
    Diagnostics = {
      ClassStaticMemberCheck = true,
      ParamsCheck = true,
    },
    DisableV1Script = true,
    FormatOptions = {
      break_chained_methods = false,
      ignore_comment = false,
      indent_string = "\t",
      keep_array_indentation = true,
      max_preserve_newlines = 2,
      one_true_brace = "1",
      preserve_newlines = true,
      space_before_conditional = true,
      space_in_empty_paren = false,
      space_in_other = true,
      space_in_paren = false,
      wrap_line_length = 0,
    },
    InterpreterPath = "C:/Program Files/Autohotkey/v2/AutoHotkey64.exe",
    SymbolFoldingFromOpenBrace = false,
  },
  single_file_support = true,
  flags = { debounce_text_changes = 500 },
}
